# GET http://localhost:3000/user
GET https://nfc-health-securty-production.up.railway.app/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6OCwiaWF0IjoxNjg0NDYwNDY5LCJleHAiOjE2ODQ1MzI0Njl9.o3UNQRxuo-p0KrZe-bE8fqCMzhs-fYOPtOEvjaJjNJo
