version: '3.1'

services:
  security_nfc_db:
    image: mysql:5.7

    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql

    command: --init-file /docker-entrypoint-initdb.d/init.sql

    ports:
      - '3312:3306'

    environment:
      MYSQL_DATABASE: security_nfc_db
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_USER: user
      MYSQL_PASSWORD: secret
