POST http://localhost:3000/nfc/read/9
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6OSwiaWF0IjoxNjg3NTM2MzM1LCJleHAiOjE2ODc2MDgzMzV9.AtB8xKCEdA1nN-L7rlP1ZYDGmW7cDtOIY20Lju6t3uA
Content-Type: application/json

{
  "nfc_payload": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXlsb2FkIjoiMTIz8J-QtDMyMSIsImlhdCI6MTY4NzUzNjIxMiwiZXhwIjoxNjg3NjA4MjEyfQ.9ATIe1gfOIiqp5L-JzJ-EENnfA5JU4pOd6WxKObrIk0"
}
