POST http://localhost:3000/nfc/read/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNjg4MjM2MDkzLCJleHAiOjE2OTA4MjgwOTN9.10wUPo2G6frXVGczaN8TriWOO3dQFufGw5UnFd8Jt_0
Content-Type: application/json

{
  "nfc_uid": "123",
  "nfc_payload": 1
}
