POST http://localhost:3000/nfc/register/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjg4MjM2MDQwLCJleHAiOjE2OTA4MjgwNDB9.1SMRDLF_oBOG7y0ENaa-zKyX7Ld5vhXS7anhMw4A2cM
Content-Type: application/json

{
  "nfc_uid": "123",
  "blockchain_hash": "321"
}
