POST http://localhost:3000/nfc/register/9
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6OSwiaWF0IjoxNjg3NTM2MjAxLCJleHAiOjE2ODc2MDgyMDF9.Wqv2ynrTrYmx3ov3MXQ45nlVs1x2Sn-BaA8JD-s_Rkk
Content-Type: application/json

{
  "nfc_uid": "123",
  "blockchain_hash": "321"
}
