POST http://localhost:3000/auth/login
# POST https://nfc-health-securty-production.up.railway.app/auth/login
Content-Type: application/json

#{
#  "email": "admin@hotmail.com",
#  "password": "admin"
#}

#{
#  "email": "sebastian@hotmail.com",
#  "password": "sebastian"
#}

{
  "email": "fabian@hotmail.com",
  "password": "fabian"
}
