GET http://localhost:3000/person/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjg4NTM0NDkwLCJleHAiOjE2OTExMjY0OTB9.dLkgnCiIl81xMgckcL5t9WIOUHY0yGxmvs5z5Q-uOo4

Content-Type: application/json
