PATCH http://localhost:3000/person/9

Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6OCwiaWF0IjoxNjg3NDAxNzQ0LCJleHAiOjE2ODc0NzM3NDR9.EFK6wx6eREiSP3LO5HHCS0Nsu1_NbUNyEYC7B0xfjDQ

{
  "lastname": "Ricardo",
  "phone": "3001231212",
  "sex": "F"
}
